package httpapi

import("context";"encoding/base64";"encoding/json";"io";"net/http";"strconv";"github.com/go-chi/chi/v5";"photovault/internal/authn";"photovault/internal/encrypteduploads";"photovault/internal/httperror")
type EncryptedUploadService interface{Create(context.Context,string,string)(encrypteduploads.Session,error);PutChunk(context.Context,string,string,string,int,[]byte,[]byte,int64,io.Reader)error;Get(context.Context,string,string,string)(encrypteduploads.Session,error);Cancel(context.Context,string,string,string)error;Complete(context.Context,string,string,string,encrypteduploads.CompleteInput)error}
type EncryptedUploadHandler struct{service EncryptedUploadService}
func NewEncryptedUploadHandler(s EncryptedUploadService)*EncryptedUploadHandler{return &EncryptedUploadHandler{s}}
func(h *EncryptedUploadHandler)ServeHTTP(w http.ResponseWriter,r *http.Request){http.NotFound(w,r)}
func(h *EncryptedUploadHandler)device(r *http.Request)(string,bool){d,ok:=authn.DeviceFromContext(r.Context());return d.ID,ok}
func(h *EncryptedUploadHandler)Create(w http.ResponseWriter,r *http.Request){d,ok:=h.device(r);if !ok{httperror.Write(w,401,"unauthorized","authentication failed");return};s,e:=h.service.Create(r.Context(),chi.URLParam(r,"vault_id"),d);if e!=nil{httperror.Write(w,403,"forbidden","vault access denied");return};writeJSON(w,201,map[string]any{"upload_id":s.ID,"chunk_size":encrypteduploads.ChunkSize,"expires_at":s.ExpiresAt,"protocol_version":2})}
func(h *EncryptedUploadHandler)Chunk(w http.ResponseWriter,r *http.Request){d,ok:=h.device(r);if !ok{httperror.Write(w,401,"unauthorized","authentication failed");return};i,e:=strconv.Atoi(chi.URLParam(r,"index"));n,_:=base64.RawURLEncoding.DecodeString(r.Header.Get("Chunk-Nonce"));t,_:=base64.RawURLEncoding.DecodeString(r.Header.Get("Chunk-Tag"));l,e2:=strconv.ParseInt(r.Header.Get("Chunk-Length"),10,64);if e!=nil||e2!=nil{httperror.Write(w,400,"invalid_request","invalid chunk metadata");return};if e=h.service.PutChunk(r.Context(),chi.URLParam(r,"vault_id"),chi.URLParam(r,"upload_id"),d,i,n,t,l,r.Body);e!=nil{httperror.Write(w,400,"invalid_request","chunk rejected");return};w.WriteHeader(204)}
