/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSyncRouteImport } from './routes/_app/sync'
import { Route as AppTimelineRouteImport } from './routes/_app/timeline'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppVaultsRouteImport } from './routes/_app/vaults'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsRoute = AppVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/devices': typeof AppDevicesRoute
  '/favorites': typeof AppFavoritesRoute
  '/gallery': typeof AppGalleryRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sync': typeof AppSyncRoute
  '/timeline': typeof AppTimelineRoute
  '/trash': typeof AppTrashRoute
  '/vaults': typeof AppVaultsRoute
}
export interface FileRoutesByTo {
  '/devices': typeof AppDevicesRoute
  '/favorites': typeof AppFavoritesRoute
  '/gallery': typeof AppGalleryRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sync': typeof AppSyncRoute
  '/timeline': typeof AppTimelineRoute
  '/trash': typeof AppTrashRoute
  '/vaults': typeof AppVaultsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/devices': typeof AppDevicesRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sync': typeof AppSyncRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/vaults': typeof AppVaultsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/favorites'
    | '/gallery'
    | '/search'
    | '/settings'
    | '/sync'
    | '/timeline'
    | '/trash'
    | '/vaults'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/devices'
    | '/favorites'
    | '/gallery'
    | '/search'
    | '/settings'
    | '/sync'
    | '/timeline'
    | '/trash'
    | '/vaults'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/devices'
    | '/_app/favorites'
    | '/_app/gallery'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/sync'
    | '/_app/timeline'
    | '/_app/trash'
    | '/_app/vaults'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaults': {
      id: '/_app/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AppVaultsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDevicesRoute: typeof AppDevicesRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSyncRoute: typeof AppSyncRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppTrashRoute: typeof AppTrashRoute
  AppVaultsRoute: typeof AppVaultsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDevicesRoute: AppDevicesRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSyncRoute: AppSyncRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppTrashRoute: AppTrashRoute,
  AppVaultsRoute: AppVaultsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
